### ISSUE TITLE
Writeup of rbart?

### ISSUE THREAD

**Issue by adamlauretig** [vdorie/dbarts#13]
@vdorie ,
This package is great, thank you so much for all your hard work!

I was interested in using the `rbart` function for some questions of my own, I was just curious: is there a writeup somewhere detailing the model that I could cite as a reference? 

Thank you!

**Comment by vdorie** [comment]
Hi Adam,

Thanks for the kind note! There isn't anything at the moment since I felt the math was a little straightforward but I could put something together if it would be helpful. I would recommend citing the package in the mean time.

Vince

**Comment by adamlauretig** [comment]
Vince,

No worries, there's no urgency. I mostly wanted to make sure I wasn't missing anything and to make sure I'm giving you proper credit. 

Adam
