### ISSUE TITLE
Accessing varcount

### ISSUE THREAD

**Issue by jameswagner254** [vdorie/dbarts#14]
Thanks for the useful package. I'm using the rbart_vi function. I'd like to extract the varcount information. It's returned as NULL under every configuration I've tried. 

The documentation talks about using the invisible function. I'm not familiar with this function. A worked example would be helpful.

**Comment by vdorie** [comment]
Should be added in the latest commit, 507e2821ba41122d999aa56b2fc6ca12883458e0.
