### ISSUE TITLE
Issue with mcmapply

### ISSUE THREAD

**Issue by gemma-e-moran** [vdorie/dbarts#15]
Hi, 

I'm running multiple different BART fits in parallel using `mcmapply` but I sometimes get the following error:

"Error in sampler$setControl(control) : \n  error matching rng kind string: Invalid argument\n"

This only happens if I use more than one core - I don't seem to get this error if I just use mapply. 

Thanks!

**Comment by vdorie** [comment]
Hi, can you post a minimal reproducible example so I can see how you're using it? I have a suspicion that the issue is in how the random seed is initialized with a new fork, but can't be sure and would need some more context.

Also, on what platform does the issue arise?

For example, the following runs fine on my OS X machine:

```R
require(dbarts)
require(parallel)

f <- function(x) {
  10 * sin(pi * x[,1] * x[,2]) + 20 * (x[,3] - 0.5)^2 +
    10 * x[,4] + 5 * x[,5]
}

set.seed(99)
sigma <- 1.0
n     <- 100

x  <- matrix(runif(n * 10), n, 10)
Ey <- f(x)
y  <- rnorm(n, Ey, sigma)

res <- mcmapply(bart, x.train = list(x, x), y.train = list(y, y), mc.cores = 2)
```

**Comment by gemma-e-moran** [comment]
Thanks for looking into this!  I am also using macOS Mojave 10.14.4.

Here is a minimal working example. The error doesn't always occur - maybe 50% of the time I run this code. It may be that I am trying to do too much. Note the for loop is necessary as the BART object I am fitting is itself part of a larger MCMC sampling scheme (even though here it seems redundant).

`require(parallel)
require(dbarts)

bart_parallel <- function(Y, X) {
  
  out <- bart(x.train = X, y.train = Y, x.test = matrix(0, nrow= 0, ncol = 0), 
              ntree = 50, ndpost = 50, nskip = 50, verbose = F)
  
  Y <- apply(out$yhat.train, 2, mean)
  sigma <-  mean(out$sigma)
  
  return(c(Y, sigma))
}

N <- 100
K <- 10
G <- 700
mc_cores <- 6

set.seed(99)

X <- matrix(rnorm(N * K), nrow = N, ncol = K)
B <- matrix(rnorm(G * K), nrow = G, ncol = K)

Y <- X %*% t(B) + matrix(rnorm(N * G), nrow = N, ncol = G)

Y_list <- lapply(1:G, function(x) Y[, x])
  
bart_args <- list(X = X)

for (t in 1:100) {
  fit <- mcmapply(bart_parallel, Y_list, MoreArgs = bart_args, mc.cores = mc_cores)
}
`

**Comment by vdorie** [comment]
Thanks for the example! There's definitely something there, but it it'll likely take a while to track down since it's a bit hard to get debugging information and it happens so infrequently. I'll update again when I've pinned it down.

**Comment by vdorie** [comment]
I've pushed a commit (6e1e4632c575818e7add685621762b63f753004a) that I think fixes it. Let me know if you encounter any issues.

**Comment by gemma-e-moran** [comment]
Thank you very much - it seems to be working great now!

**Comment by vdorie** [comment]
Great, glad to hear it!
