### ISSUE TITLE
xbart crashes R

### ISSUE THREAD

**Issue by cjcarlson** [vdorie/dbarts#21]
Hey Vincent-

I've been experimenting a bit with xbart and for reasons I don't fully understand, when I run it with a pretty moderate sized dataset (988 rows), it fully and immediately crashes the R session with a fatal error every time. I don't think it's anything about the data per se, which can be run through bart() normally. It happens whether it's x/y or formula, and I think invariant of the method or other specifications as well. It crashes R on both my Windows laptop and an RStudio server running Linux. I'm not sure what to do with this - do you want me to email you the dataset + code?

Thanks!

Colin

**Comment by vdorie** [comment]
Interesting. Yeah, if you can email me the data and code that would be great. `xbart` does some hacky things to enable custom R loss functions, and it wouldn't surprise me if I messed something up.

**Comment by vdorie** [comment]
Thanks! Should be fixed with fde0a6a23cd8353798fa60875e412cbcc92570df. Let me know if the problem persists.

**Comment by cjcarlson** [comment]
Wonderful!! Thank you

**Comment by cjcarlson** [comment]
Yes it does work smoothly now :)
