### ISSUE TITLE
predict errors with rbart

### ISSUE THREAD

**Issue by cjcarlson** [vdorie/dbarts#22]
Hi again! Sorry to leave so many comments lately

predict.rbart has been doing some odd stuff lately, and I think in a previous iteration I had figured out the trick was very specific syntax with the " - [ranef name]" in the formula, but it doesn't seem to work anymore. It's always the same error: 

Error in array(sapply(pred, function(x) x), c(dim(pred[[1L]]), n.chains)) +  : 
  non-conformable arrays

Any clue what this is and what causes it? I'm trying to write a standardized wrapper around predict.rbart so I want to be able to just set up a consistent syntax that doesn't break, but I don't quite understand what causes this error...

Thanks!

Colin

**Comment by vdorie** [comment]
Hi Colin,

Thanks for letting me know. I've been tweaking `predict` for `rbart` to be more natural by adding in the random effects and I might have made a mistake. If you can send along some more example code I'd be happy to take a look.

Vince

**Comment by cjcarlson** [comment]
Emailed an example with the same data!
