### ISSUE TITLE
'group.by' not of length equal to that of data

### ISSUE THREAD

**Issue by rsparapa** [vdorie/dbarts#24]
Hi Gang:

Hi Vincent:

I keep running into this error message.  There must be something that I don't understand.  I tried the simple example in the docs and it works.  But, when I get to real data, something goes haywire.  How can I debug this?  I looked at the rbart_vi function, but your script fu is too much for me.  Is there a simple way to attack this?

Thanks,

Rodney

**Comment by vdorie** [comment]
If you can give me a "minimal working example", or just your code and data, I can take a look. If I had to guess, the code I've hacked to try to find the grouping variable isn't finding the correct reference, and whatever it is finding happens to have the wrong length.

The easiest way to run `rbart_vi` seems to be to create a data frame (`df`) with a response (`y`), the grouping var (`g`), and everything else. Then run:
```R
rbartFit <- rbart_vi(y ~ . - g, data = df, group.by = g)
```
As I move to a full `lme4`-style solution with grouping variables in the formula, hopefully it will get easier to run.

**Comment by rsparapa** [comment]
Hi Vincent:

Unfortunately, the data is proprietary and I can't share it.  My testing with fake data is working so I'm not sure where the disconnect is.  That's why I was asking how to debug this.  However, I am very much looking forward to your improvements.  I will be watching your lme4-like transformation with interest.

Thanks,

Rodney
