### ISSUE TITLE
`sample.kind = "Rejection"` not available in older versions of R

### ISSUE THREAD

**Issue by michaelquinn32** [vdorie/dbarts#30]
Hi Vincent!

In `tests/testthat/test-10-makeModelMatrix.R`, the test that "make model matrix handles character vectors correctly" sets `sample.kind = "Rejection"`. This value is unavailable in older versions of R.

One fix to this problem is to add a skip, `testthat::skip_if_not(getRversion() >= 3.6)`. Otherwise, let me know if there is more that I can do to help with this.

Thanks!
Michael

**Comment by vdorie** [comment]
Thanks, fixed in repo!
