### ISSUE TITLE
Reproducible multithreaded models

### ISSUE THREAD

**Issue by bachlaw** [vdorie/dbarts#38]
Vince, you may already be working on this, if the repo updates are any indication, but I've noticed that while a single threaded run of `dbarts` can be reproducible merely by setting the seed before starting, with a multi-threaded run that doesn't work.  

What is the simplest way to establish reproducibility over multiple threads, using `dbarts`?  

Thanks very much.

**Comment by vdorie** [comment]
Howdy. Should have been added with fc4b6d3e1cba37ec689b9a4070f13ae2bbbaa89d. Not on CRAN yet, but will be soon.

**Comment by bachlaw** [comment]
Wow, talk about a prompt response! I'll integrate this. Thanks very much.

Jonathan
