### ISSUE TITLE
rbart_vi group parsing issues

### ISSUE THREAD

**Issue by bachlaw** [vdorie/dbarts#42]
Hi Vince,

Having some issues with groups not appearing to parse correctly.  

Reproducible examples:

```library(dbarts)
packageVersion("dbarts")
#[1] ‘0.9.20’

### try group as factor first ###

set.seed(1234)

x1 <- rnorm(2.5e3, -.3)
x2 <- rnorm(2.5e3, .2)
x3 <- rpois(2.5e3, 1)

y <- rbinom(2.5e3, 1, .6)
y2 <- rnorm(2.5e3, 0)

g <- factor(sample(1:50, 2.5e3, replace=TRUE))

df <- data.frame(x1, x2, x3, y, g)
df.train <- df[1:1500,]
df.test <- df[1501:2.5e3,]

set.seed(1234)
bart.1 <- bart2(y ~ ., data=df.train, test=df.test) 

### try group as random effect ###

set.seed(1234)
bart.2 <- rbart_vi(y ~ . -g, data=df.train, test=df.test, group.by = g, group.by.test = g)
```
`bart.1` works fine. 

The error message I get for `bart.2` is:

```Error in rbart_vi(y ~ . - g, data = df.train, test = df.test, group.by = g,  : 
  'group.by' not of length equal to that of data
```

Any thoughts on what about my inputs might be upsetting the bart parsing functions? My sample data seems to mirror the concepts in the function example but the factor variable is not being perceived as a viable column of data. Changing `g` to an integer (not shown) did not make a difference.

Thanks,
Jonathan

**Comment by vdorie** [comment]
Hi Jonathan,

The problem has to do with `` `g` `` being defined in the calling environment, and in the `data` frame. Currently, it is looking first for the grouping variable in the calling environment and only in `data` if it can't be found there. Since this doesn't seem to conform to expectations, I'll work on reversing the order. Until then, you can get the example to run by executing:

```
set.seed(1234)
g.train <- df.train$g
g.test  <- df.test$g
bart.2 <- rbart_vi(y ~ . -g, data=df.train, test=df.test, group.by = g.train, group.by.test = g.test)
```

**Comment by vdorie** [comment]
Default behavior should be now changed as of 76196ed962f72f2debd71df3fa4ff7c81cc7d612.

**Comment by bachlaw** [comment]
Can confirm that it now works fine with both the reprex and real data with a different factor variable as the group. Many thanks.

**Comment by vdorie** [comment]
Great, thanks!
