### ISSUE TITLE
Problem with the length of weights

### ISSUE THREAD

**Issue by Pentaonia** [vdorie/dbarts#57]
Hi, 
im trying to run this code:

```
model <- rbart_vi(
        formula = modform, 
        group.by = seq(1,nrow(PA_train),1), 
        group.by.test = seq(1,nrow(PA_test),1),
        data = PA_train, 
        test = PA_test, 
        weights = my_weights,
        keepTrees = T, 
        n.samples = 40L, 
        n.burn = 10L, 
        n.thin = 2L, 
        n.chains = 1L,
        n.trees = 25L, 
        n.threads = dbarts::guessNumCores()-1, 
        combineChains = T
    )
```

it is running fine as long as I exclude the "weights". When I include them, a error pops up:
```
Error in model.frame.default(formula = ...  : 
  variable lengths differ (found for '(weights)')
```

But `nrow(PA_train) == length(weights)` therefore I have no Idea whats going on there. My weights are a vector of values ]0,1]. 

My dataset is based on presence/absence data (pa), so 0 and 1 and the formula is something like this: pa ~ slope + bio_12 + bio_1 + bio_4 + trees - shrubs.

Hopefully there is someone out there who can help me because I need this in my masters thesis.

Best
Loubert

I use this system:
```
platform       x86_64-w64-mingw32
arch           x86_64
crt            ucrt
system         x86_64, mingw32
status
major          4
minor          2.3
year           2023
month          03
day            15
svn rev        83980
language       R
version.string R version 4.2.3 (2023-03-15 ucrt)
nickname       Shortstop Beagle
```

**Comment by n8layman** [comment]
I'm still a bit confused. In the above case, if you didn't want to nullify it how would you specify weights for both PA_train and PA_test? There is only one weights argument.

**Comment by Pentaonia** [comment]
> I'm still a bit confused. In the above case, if you didn't want to nullify it how would you specify weights for both PA_train and PA_test? There is only one weights argument.

That's where I struggled too! 
At the end I decided to leave the test data out and do several tests "outside" of the model. 
But yeah, it would be great to kind of "reopen" that. Or is it implemented but we do not know how to deal with that?

Best
Louis
