### ISSUE TITLE
keepevery is ignored in dbarts 0.8-5

### ISSUE THREAD

**Issue by rsparapa** [vdorie/dbarts#6]
Great package, very fast!  However, keepevery appears to be ignored.  You can workaround this by manually thinning.  But, if you are calling dbarts in parallel, then you can easily tickle the R bug when you go over 2B elements in a matrix, e.g. Error in sendMaster(try(eval(expr, env), silent = TRUE)) : long vectors not supported yet: fork.c:376
For example, suppose that you have an x.test matrix with 210000 records and you request ndpost=10000 samples which results in a yhat.test matrix with 10000 rows and 210000 columns since keepevery=10 is ignored.  You will have a run that starts fine and everything appears to be going well until the run just about finishes and abends with an error message something like the above.  This will be addressed if keepevery=10 works as documented since the result will be yhat.test with 1000 rows and 210000 columns.  Looking over the dbarts code, yhat.test thinning appears to be handled in src/dbarts/bartFit.cpp line 454, but I am not following the code there and don't see why it is not happening.  Any hints?  Also, it appears to be ignored for yhat.train as well; again looking over the code I don't see why.  Please don't hesitate to contact him if you have any comments/questions/etc.

**Comment by vdorie** [comment]
`keepevery` should be working as it did in the original BayesTree, in which you get `ndpost` samples regardless, while the total number of samples generated internally is (`ndpost` + `nskip`) * `keepevery`.  The relevant line of `bartFit.cpp` is 409:

  size_t totalNumIterations = (numBurnIn + numSamples) * control.treeThinningRate;

I haven't had a chance to go back and manually add print statements to guarantee that it is behaving as correctly, but running the model in the help files with keepevery = 100 seems to take about 100 times as long.

**Comment by rsparapa** [comment]
Are you sure about that?  I seem to be getting ndpost*keepevery samples.  And, I have a colleague here who is experiencing the same issue: hence are issue report.

**Comment by vdorie** [comment]
Fixed in the new version, now on CRAN. Thanks for bringing this to my attention.
