### ISSUE TITLE
installation failure on Alpine Linux

### ISSUE THREAD

**Issue by bastistician** [vdorie/dbarts#68]
Installation of 'dbarts' currently fails under musl libc, e.g., on Alpine Linux.
I see:
```
guessNumCores.cpp:212:38: error: invalid conversion from 'int' to 'char*' [-fpermissive]
  212 |       char* errorMessage = strerror_r(errno, errorBuffer, ERROR_BUFFER_LENGTH);
      |                            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      int
guessNumCores.cpp:248:38: error: invalid conversion from 'int' to 'char*' [-fpermissive]
  248 |       char* errorMessage = strerror_r(errno, errorBuffer, ERROR_BUFFER_LENGTH);
      |                            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      int
```

In both cases, the code already implements a switch for the GNU-specific implementation of `strerror_r()`:
https://github.com/vdorie/dbarts/blob/7d93c4aee0ed2b1c88604fbc8041f906a8e4101e/src/guessNumCores.cpp#L211-L217
However, it seems this is not sufficient to get in the right track under musl. Even with `_GNU_SOURCE` defined, musl will stick to the XSI-compliant version and this is by design, see, e.g. <https://www.openwall.com/lists/musl/2018/08/05/2>.

The following, more specific condition works for me:
```c
#if defined(__GLIBC__) && defined(_GNU_SOURCE)
```

**Comment by bastistician** [comment]
As 'dbarts' already has a configure script anyway, a much better solution would be to simply use the macro `AC_FUNC_STRERROR_R`:

> If [`strerror_r`] returns a char * message, define `STRERROR_R_CHAR_P`.

**Comment by vdorie** [comment]
Hopefully fixed in `0b4190d`. Please let me know if it doesn't work.

**Comment by vdorie** [comment]
Thanks, sorry that I missed that! Trying again with [c10b436](https://github.com/vdorie/dbarts/commit/c10b43678b992bc1771b7a288a8f958b0f97bb00).

**Comment by bastistician** [comment]
Thanks for taking care of this portability issue.
I can confirm that c10b436 can be installed on Alpine Linux and run-time checks are all OK.

**Comment by vdorie** [comment]
Great, thank you!

**Comment by bastistician** [comment]
Any plans to release the fixed version on CRAN? Currently, `install.packages("dbarts")` fails on musl-based systems; similarly for the reverse dependencies ... Thanks!

**Comment by vdorie** [comment]
It should be working its way through CRAN now.
