### ISSUE TITLE
problem with univariate `x` in data.frame

### ISSUE THREAD

**Issue by benkeser** [vdorie/dbarts#8]
Just noticed a bug in calls to `bart` when `x` is a univariate `data.frame`. Below is an example that reproduces. 
```r
n  <- 200
x <- data.frame(x = runif(n))
y <- x$x + rnorm(n)
# works
good_fit <- bart(x$x, y)
# doesn't work
bad_fit <- bart(x, y)
```

The error message is 
```r
Error in attr(x, attributeName) <- attr(formula, attributeName) : 
  'dimnames' applied to non-array
```

As best as I can debug it, the error seems to crop up from the call to `C_dbarts_makeModelMatrixFromDataFrame`. If you check `attributes(result)` after the line 
```r
result <- .Call(C_dbarts_makeModelMatrixFromDataFrame, x, drop)
```
you'll see that `$dimnames` returns as a list with `NULL` first entry. This causes an error later when this bit executes for the `$dimnames` entry of `attributes(formula)`. 
```r
if (length(attributes(formula)) > 0L) for (attributeName in names(attributes(formula))) {
    if (attributeName == "dim") 
        next
    attr(x, attributeName) <- attr(formula, attributeName)
}
```

**Comment by vdorie** [comment]
Thanks for the extremely concise, reproducible example. I've checked in something that seems to fix the problem and will see about submitting to CRAN in a few weeks, after I do some other work on the package.

**Comment by benkeser** [comment]
Thanks!
